"""
Parser for conclusion.md files generated by product committee.

Extracts revision items from the conclusion file and converts them
to RevisionItem domain entities.
"""
import re
import logging
from typing import List, Optional
from pathlib import Path

from ..domain.entities import RevisionItem
from ..domain.value_objects import RevisionAction


logger = logging.getLogger(__name__)


class ConclusionParser:
    """
    Parses conclusion.md files to extract revision items.

    Handles the specific format generated by Deb8flow's product committee:
    - Russian headers ("## Рекомендации")
    - Numbered list items with optional room tags
    - Markdown formatting
    """

    # Patterns for parsing
    RECOMMENDATIONS_SECTION = re.compile(r"^##\s*Рекомендации", re.MULTILINE)
    REVISION_ITEM_PATTERN = re.compile(r"^\d+\.\s+(.+?)\s*\[(\w+)\]?\s*$", re.MULTILINE)

    def __init__(self, encoding: str = "utf-8"):
        """
        Initialize parser.

        Args:
            encoding: File encoding to use (default: utf-8)
        """
        self.encoding = encoding

    def parse(self, conclusion_path: Path) -> List[RevisionItem]:
        """
        Parse conclusion.md and extract revision items.

        Args:
            conclusion_path: Path to conclusion.md file

        Returns:
            List of RevisionItem objects extracted from the file

        Raises:
            FileNotFoundError: If conclusion file doesn't exist
            ValueError: If file contains no parseable revisions
        """
        if not conclusion_path.exists():
            raise FileNotFoundError(f"Conclusion file not found: {conclusion_path}")

        # Read file content
        content = self._read_file(conclusion_path)

        # Extract recommendations section
        recommendations_text = self._extract_recommendations_section(content)

        if not recommendations_text:
            raise ValueError(
                f"No '## Рекомендации' section found in {conclusion_path}. "
                f"Ensure the file follows the expected format."
            )

        # Try standard parser first
        revisions = self._parse_revision_items(recommendations_text)

        # Try fallback if standard parser found nothing
        if not revisions:
            logger.warning(f"Standard parser found no items, trying fallback")
            revisions = self._parse_with_fallback(recommendations_text)

        if not revisions:
            raise ValueError(
                f"No parseable revision items found in {conclusion_path}. "
                f"Expected format: '1. Recommendation text [Room]'"
            )

        logger.info(f"Parsed {len(revisions)} revision items from {conclusion_path}")
        return revisions

    def _read_file(self, path: Path) -> str:
        """Read file content with encoding fallback."""
        encodings = [self.encoding, "cp1251", "iso-8859-1", "windows-1252"]

        for encoding in encodings:
            try:
                return path.read_text(encoding=encoding)
            except (UnicodeDecodeError, UnicodeError):
                continue

        raise RuntimeError(f"Could not decode file: {path}")

    def _extract_recommendations_section(self, content: str) -> Optional[str]:
        """
        Extract the recommendations section from conclusion content.

        Args:
            content: Full conclusion file content

        Returns:
            Recommendations section text, or None if not found
        """
        match = self.RECOMMENDATIONS_SECTION.search(content)
        if not match:
            return None

        # Get text from match to end of file (or next section)
        start_pos = match.end()
        remaining_content = content[start_pos:]

        # Stop at next major section or end of file
        next_section = re.search(r"\n^##\s+", remaining_content, re.MULTILINE)
        if next_section:
            return remaining_content[:next_section.start()]

        return remaining_content

    def _parse_revision_items(self, text: str) -> List[RevisionItem]:
        """
        Parse revision items from recommendations text.

        Args:
            text: Recommendations section text

        Returns:
            List of RevisionItem objects
        """
        revisions = []
        lines = text.strip().split("\n")

        for line_num, line in enumerate(lines, 1):
            line = line.strip()
            if not line:
                continue

            # Try to match numbered item format
            match = self.REVISION_ITEM_PATTERN.match(line)
            if match:
                content_text = match.group(1).strip()
                room_tag = match.group(2) if match.group(2) else "general"

                # Create RevisionItem
                revision = RevisionItem(
                    id=f"REV{len(revisions) + 1:03d}",
                    content=content_text,
                    section=room_tag,
                    action=RevisionAction.UPDATE,  # Default action
                    verified=False
                )
                revisions.append(revision)
            else:
                # Log warning but don't fail
                logger.warning(f"Could not parse line {line_num}: '{line[:50]}...'")

        return revisions

    def _parse_with_fallback(self, text: str) -> List[RevisionItem]:
        """
        Fallback parser for non-standard conclusion formats.

        Tries multiple strategies to extract revision items:
        1. Standard numbered list with tags
        2. Numbered list without tags
        3. Bullet points
        4. All lines as individual items

        Args:
            text: Recommendations section text

        Returns:
            List of RevisionItem objects
        """
        revisions = []

        # Try standard format first
        revisions = self._parse_revision_items(text)
        if revisions:
            return revisions

        # Fallback 1: Numbered items without room tags
        pattern = re.compile(r"^\d+\.\s+(.+)$", re.MULTILINE)
        matches = pattern.findall(text)
        if matches:
            for i, content in enumerate(matches):
                revisions.append(RevisionItem(
                    id=f"REV{i + 1:03d}",
                    content=content.strip(),
                    section="general",
                    action=RevisionAction.UPDATE
                ))
            logger.warning(f"Used fallback parser (numbered items without tags)")
            return revisions

        # Fallback 2: Bullet points
        pattern = re.compile(r"^[\-\*]\s+(.+)$", re.MULTILINE)
        matches = pattern.findall(text)
        if matches:
            for i, content in enumerate(matches):
                revisions.append(RevisionItem(
                    id=f"REV{i + 1:03d}",
                    content=content.strip(),
                    section="general",
                    action=RevisionAction.UPDATE
                ))
            logger.warning(f"Used fallback parser (bullet points)")
            return revisions

        # Fallback 3: All non-empty lines
        lines = [l.strip() for l in text.split("\n") if l.strip()]
        lines = [l for l in lines if not l.startswith("#")]  # Skip headers
        if lines:
            for i, content in enumerate(lines):
                revisions.append(RevisionItem(
                    id=f"REV{i + 1:03d}",
                    content=content,
                    section="general",
                    action=RevisionAction.UPDATE
                ))
            logger.warning(f"Used fallback parser (all lines)")
            return revisions

        return []
